main: main.o socket_cross_roads.o
	g++ main.o socket_cross_roads.o -o main
main.o:main.cpp
	g++ -c main.cpp -o main.o
socket_cross_roads.o:socket_cross_roads.cpp
	g++ -c socket_cross_roads.cpp -o socket_cross_roads.o
